/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JogadoresRouteImport } from './routes/jogadores'
import { Route as SessoesIndexRouteImport } from './routes/sessoes.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JogadoresRoute = JogadoresRouteImport.update({
  id: '/jogadores',
  path: '/jogadores',
  getParentRoute: () => rootRouteImport,
} as any)
const SessoesIndexRoute = SessoesIndexRouteImport.update({
  id: '/sessoes/',
  path: '/sessoes/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/jogadores': typeof JogadoresRoute
  '/sessoes/': typeof SessoesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/jogadores': typeof JogadoresRoute
  '/sessoes': typeof SessoesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/jogadores': typeof JogadoresRoute
  '/sessoes/': typeof SessoesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/jogadores' | '/sessoes/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/jogadores' | '/sessoes'
  id: '__root__' | '/' | '/jogadores' | '/sessoes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JogadoresRoute: typeof JogadoresRoute
  SessoesIndexRoute: typeof SessoesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogadores': {
      id: '/jogadores'
      path: '/jogadores'
      fullPath: '/jogadores'
      preLoaderRoute: typeof JogadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessoes/': {
      id: '/sessoes/'
      path: '/sessoes'
      fullPath: '/sessoes/'
      preLoaderRoute: typeof SessoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JogadoresRoute: JogadoresRoute,
  SessoesIndexRoute: SessoesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
